#!/usr/bin/env bash

# Check if /etc/lightdm/slick-greeter.conf exists
if [ -f /etc/lightdm/slick-greeter.conf ]; then
    # If it exists, create a backup
    cp -f /etc/lightdm/slick-greeter.conf /etc/lightdm/slick-greeter.conf.bak
fi

# Copy the custom configuration file
cp -f /etc/lightdm/slick-greeter.conf.big /etc/lightdm/slick-greeter.conf
